#!/usr/bin/env python

import sys

def options(opt):
        opt.load('compiler_cxx')
        opt.load('compiler_c')

def configure(conf):
	conf.load('compiler_cxx')
	conf.load('compiler_c')
	conf.define('XTRACT_FFT', 1)

def build(bld):
	bld.program(
		source       = bld.path.ant_glob('src/**/*.cpp') 
                        + bld.path.ant_glob('src/**/*.c'),
		target       = 'gppsound',
		includes     = ['/usr/include','/usr/local/include','src'], 
		lib          = ['m','jack','pthread','sndfile', 'fftw3','fftw3f'],
		libpath      = ['/usr/lib','/usr/local/lib'],
		vnum         = '0.0.1',
		install_path = '${SOME_PATH}/bin',
		cxxflags     = ['-O3','-Wall']
	)

